/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Asignacion;
import controlador.RegistroAsignacion;

/**
 *
 * @author andre
 */
public class Form_asignarEquipo extends javax.swing.JFrame {

    /**
     * Creates new form Form_asignarEquipo
     */
    public Form_asignarEquipo() {
        initComponents();
    }

    private RegistroAsignacion registroAsignacion = new RegistroAsignacion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_npiUsuario = new javax.swing.JTextField();
        jtxt_nusEquipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_firmaUsuario = new javax.swing.JTextField();
        jbtn_asignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asignar Equipo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresar ID Usuario");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar ID inventario");

        jtxt_npiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_npiUsuarioActionPerformed(evt);
            }
        });

        jtxt_nusEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nusEquipoActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Firma");

        jtxt_firmaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_firmaUsuarioActionPerformed(evt);
            }
        });

        jbtn_asignar.setText("Asignar");
        jbtn_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_asignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_nusEquipo)
                    .addComponent(jtxt_firmaUsuario)
                    .addComponent(jtxt_npiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addComponent(jbtn_asignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_npiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_nusEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_firmaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtn_asignar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_npiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_npiUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_npiUsuarioActionPerformed

    private void jtxt_nusEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nusEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nusEquipoActionPerformed

    private void jtxt_firmaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_firmaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_firmaUsuarioActionPerformed

    private void jbtn_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_asignarActionPerformed
        // Obtener los valores de los campos de texto y otros componentes
        String firma = jtxt_firmaUsuario.getText();
        int idUsuario = obtenerIdUsuario();  // Deberías tener un método para obtener el ID del usuario seleccionado
        int idEquipo = obtenerIdEquipo();    // Deberías tener un método para obtener el ID del equipo seleccionado

        // Crear un objeto Asignacion con los datos ingresados
        Asignacion asignacion = new Asignacion();
        asignacion.setFirma(firma);
        asignacion.setId_inventario(idEquipo);
        asignacion.setId_usuario(idUsuario);

        // Realizar la asignación llamando al método en el controlador
        if (registroAsignacion.asignarEquipo(asignacion)) {
            JOptionPane.showMessageDialog(null, "Equipo asignado correctamente");
            // Puedes agregar aquí cualquier lógica adicional que desees después de asignar el equipo
        } else {
            JOptionPane.showMessageDialog(null, "Error al asignar el equipo");
        }


    }//GEN-LAST:event_jbtn_asignarActionPerformed

    private int obtenerIdUsuario() {
        try {
            // Obtener el ID del usuario desde el campo de texto
            return Integer.parseInt(jtxt_npiUsuario.getText());
        } catch (NumberFormatException e) {
            // Manejar la excepción si el valor no es un número entero válido
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido para el ID de usuario", "Error", JOptionPane.ERROR_MESSAGE);
            return -1;  // o algún valor que indique que no se pudo obtener el ID
        }
    }

    private int obtenerIdEquipo() {
        try {
            // Obtener el ID del equipo desde el campo de texto
            return Integer.parseInt(jtxt_nusEquipo.getText());
        } catch (NumberFormatException e) {
            // Manejar la excepción si el valor no es un número entero válido
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido para el ID del equipo", "Error", JOptionPane.ERROR_MESSAGE);
            return -1;  // o algún valor que indique que no se pudo obtener el ID
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_asignarEquipo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_asignarEquipo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_asignarEquipo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_asignarEquipo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_asignarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtn_asignar;
    private javax.swing.JTextField jtxt_firmaUsuario;
    private javax.swing.JTextField jtxt_npiUsuario;
    private javax.swing.JTextField jtxt_nusEquipo;
    // End of variables declaration//GEN-END:variables
}
